// Generated by scripts/optimize-story-photos.mjs — do not edit
export const PHOTO_VERSIONS: Record<number, number> = {
  "1": 1782571110296,
  "2": 1782571110980,
  "3": 1782571111252,
  "4": 1782571111462,
  "5": 1782571111655,
  "6": 1782571112136,
  "7": 1782571112384,
  "8": 1782571112517,
  "9": 1782571112652,
  "10": 1782571112903
};
